- hosts: all
  tasks:
    - name: initDir
      file: path=/AIOPS state=directory owner=root group=root
      file: path=/AIOPS/CMDB state=directory owner=root group=root

    - name: copyAssetScripts
      copy: src=/AIOPS_PLATFORM/CMDB/asset dest=/AIOPS/CMDB/ owner=root group=root mode=0755
